/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GPS;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class GPS extends javax.swing.JFrame {
         
    
    
    Fondo fondo = new Fondo();
    /**
     * Creates new form NewJFrame
     */
    public GPS() {
        //this.setContentPane(fondo);
       
        initComponents();
         
         this.setBounds(0, 0, 1350, 750);
         this.setLocationRelativeTo(null);
        
        
         new Thread(){
            public void run(){
            
                int x = 150;
                
                int z = Juan.getLocation().y;
                
                while(true){
                x++;
                 if(x > getWidth()){
                      x=0;}
                  
                  Juan.setLocation(x, 300);
                 try{
                     sleep(500);
                 }
                 catch(Exception e){}
                 
                }
            
            }
        }.start();
        
         new Thread(){
            public void run(){
            
                int y = 200;
                int x = maria.getLocation().y;
                
                
                while(true){
                y++;
                 if(y > getHeight()){
                      y=0;}
                  maria.setLocation(600, y);
                  
                 try{
                     sleep(500);
                 }
                 catch(Exception e){}
                 
                }
            
            }
        }.start();
         new Thread(){
            public void run(){
            
                int x = 1200;
                
                int z = Carlos.getLocation().y;
                
                while(true){
                x--;
                 if(x > getWidth()){
                      x=0;}
                  
                  Carlos.setLocation(x, 400);
                 try{
                     sleep(500);
                 }
                 catch(Exception e){}
                 
                }
            
            }
        }.start();
         new Thread(){
            public void run(){
            
                int y = 500;
                int x = jose.getLocation().y;
                
                
                while(true){
                y--;
                 if(y > getHeight()){
                      y=0;}
                  jose.setLocation(800, y);
                  
                 try{
                     sleep(400);
                 }
                 catch(Exception e){}
                 
                }
            
            }
        }.start();
          new Thread(){
            public void run(){
            
                int y = 700;
                int x = pilar.getLocation().y;
                
                
                while(true){
                y--;
                 if(y > getHeight()){
                      y=0;}
                  pilar.setLocation(850, y);
                  
                 try{
                     sleep(60);
                 }
                 catch(Exception e){}
                 
                }
            
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapa = new Fondo();
        jLabel2 = new javax.swing.JLabel();
        Juan = new javax.swing.JLabel();
        Carlos = new javax.swing.JLabel();
        pilar = new javax.swing.JLabel();
        maria = new javax.swing.JLabel();
        jose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));

        mapa.setAlignmentX(0.0F);
        mapa.setAlignmentY(0.0F);
        mapa.setPreferredSize(new java.awt.Dimension(1350, 750));

        Juan.setText("JUAN");

        Carlos.setText("CARLOS");

        pilar.setText("pilar");

        maria.setText("maria");

        jose.setText("jose");

        javax.swing.GroupLayout mapaLayout = new javax.swing.GroupLayout(mapa);
        mapa.setLayout(mapaLayout);
        mapaLayout.setHorizontalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addGroup(mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapaLayout.createSequentialGroup()
                        .addComponent(Carlos)
                        .addGap(59, 59, 59)
                        .addComponent(Juan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapaLayout.createSequentialGroup()
                        .addGroup(mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pilar)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addComponent(maria)))
                .addContainerGap(841, Short.MAX_VALUE))
            .addGroup(mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mapaLayout.createSequentialGroup()
                    .addGap(425, 425, 425)
                    .addComponent(jose)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );
        mapaLayout.setVerticalGroup(
            mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilar)
                    .addComponent(maria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Juan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mapaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carlos)))
                .addContainerGap(610, Short.MAX_VALUE))
            .addGroup(mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mapaLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jose)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carlos;
    private javax.swing.JLabel Juan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jose;
    private javax.swing.JPanel mapa;
    private javax.swing.JLabel maria;
    private javax.swing.JLabel pilar;
    // End of variables declaration//GEN-END:variables
public class Fondo extends JPanel{
   private Image imagen;
   
   public void paint(Graphics g){
   
     imagen = new ImageIcon(getClass().getResource("Cali2.jpg")).getImage();
     g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
     setOpaque(false);
     super.paint(g);
   }

}

}
