/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Steven
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        ventasycompras = new javax.swing.JPanel();
        btncompras = new javax.swing.JButton();
        btnventas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        clientesyempleados = new javax.swing.JPanel();
        btnclientes = new javax.swing.JButton();
        btnempleados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuControlProductos = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenu();
        itemCrear = new javax.swing.JMenuItem();
        itemLeer = new javax.swing.JMenuItem();
        itemActualizar = new javax.swing.JMenuItem();
        itemBorrar = new javax.swing.JMenuItem();
        menuProduccion = new javax.swing.JMenu();
        itemCrear1 = new javax.swing.JMenuItem();
        itemLeer1 = new javax.swing.JMenuItem();
        itemActualizar1 = new javax.swing.JMenuItem();
        itemBorrar1 = new javax.swing.JMenuItem();
        itemIngredientes = new javax.swing.JMenu();
        itemCrear2 = new javax.swing.JMenuItem();
        itemLeer2 = new javax.swing.JMenuItem();
        itemActualizar2 = new javax.swing.JMenuItem();
        itemBorrar2 = new javax.swing.JMenuItem();
        menuControlMateriaPrima = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventasycompras.setBorder(javax.swing.BorderFactory.createTitledBorder("Transacciones"));
        ventasycompras.setName("Transacciones"); // NOI18N

        btncompras.setText("Compras");

        btnventas.setText("Ventas");

        javax.swing.GroupLayout ventasycomprasLayout = new javax.swing.GroupLayout(ventasycompras);
        ventasycompras.setLayout(ventasycomprasLayout);
        ventasycomprasLayout.setHorizontalGroup(
            ventasycomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasycomprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventasycomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncompras)
                    .addComponent(btnventas))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ventasycomprasLayout.setVerticalGroup(
            ventasycomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasycomprasLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncompras)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        clientesyempleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        btnclientes.setText("Clientes");

        btnempleados.setText("Empleados");

        javax.swing.GroupLayout clientesyempleadosLayout = new javax.swing.GroupLayout(clientesyempleados);
        clientesyempleados.setLayout(clientesyempleadosLayout);
        clientesyempleadosLayout.setHorizontalGroup(
            clientesyempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesyempleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnempleados)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        clientesyempleadosLayout.setVerticalGroup(
            clientesyempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesyempleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientesyempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclientes)
                    .addComponent(btnempleados))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        menuControlProductos.setText("Control de Productos");

        menuProductos.setText("Productos");

        itemCrear.setText("Crear");
        itemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearActionPerformed(evt);
            }
        });
        menuProductos.add(itemCrear);

        itemLeer.setText("Leer");
        itemLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLeerActionPerformed(evt);
            }
        });
        menuProductos.add(itemLeer);

        itemActualizar.setText("Actualizar");
        itemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarActionPerformed(evt);
            }
        });
        menuProductos.add(itemActualizar);

        itemBorrar.setText("Borrar");
        itemBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBorrarActionPerformed(evt);
            }
        });
        menuProductos.add(itemBorrar);

        menuControlProductos.add(menuProductos);

        menuProduccion.setText("Produccion");

        itemCrear1.setText("Crear");
        menuProduccion.add(itemCrear1);

        itemLeer1.setText("Leer");
        menuProduccion.add(itemLeer1);

        itemActualizar1.setText("Actualizar");
        menuProduccion.add(itemActualizar1);

        itemBorrar1.setText("Borrar");
        itemBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBorrar1ActionPerformed(evt);
            }
        });
        menuProduccion.add(itemBorrar1);

        menuControlProductos.add(menuProduccion);

        itemIngredientes.setText("Ingredientes");

        itemCrear2.setText("Crear");
        itemIngredientes.add(itemCrear2);

        itemLeer2.setText("Leer");
        itemIngredientes.add(itemLeer2);

        itemActualizar2.setText("Actualizar");
        itemIngredientes.add(itemActualizar2);

        itemBorrar2.setText("Borrar");
        itemBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBorrar2ActionPerformed(evt);
            }
        });
        itemIngredientes.add(itemBorrar2);

        menuControlProductos.add(itemIngredientes);

        jMenuBar1.add(menuControlProductos);

        menuControlMateriaPrima.setText("Control Materia Prima");

        jMenuItem4.setText("Materia Prima");
        menuControlMateriaPrima.add(jMenuItem4);

        jMenuBar1.add(menuControlMateriaPrima);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientesyempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ventasycompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventasycompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientesyempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBorrarActionPerformed
        // TODO add your handling code here:
        DeleteProducto deleteProducto = new DeleteProducto(this, true);
        deleteProducto.setVisible(true);
    }//GEN-LAST:event_itemBorrarActionPerformed

    private void itemBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBorrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBorrar1ActionPerformed

    private void itemBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBorrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBorrar2ActionPerformed

    private void itemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearActionPerformed
        // TODO add your handling code here:
        AddProducto addProducto = new AddProducto(this,true);
        addProducto.setVisible(true);
    }//GEN-LAST:event_itemCrearActionPerformed

    private void itemLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLeerActionPerformed
        // TODO add your handling code here:
        ReadProducto readProducto = new ReadProducto(this, true);
        readProducto.setVisible(true);
    }//GEN-LAST:event_itemLeerActionPerformed

    private void itemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarActionPerformed
        // TODO add your handling code here:
        UpdateProducto updateProducto = new UpdateProducto(this, true);
        updateProducto.setVisible(true);
    }//GEN-LAST:event_itemActualizarActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btncompras;
    private javax.swing.JButton btnempleados;
    private javax.swing.JButton btnventas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel clientesyempleados;
    private javax.swing.JMenuItem itemActualizar;
    private javax.swing.JMenuItem itemActualizar1;
    private javax.swing.JMenuItem itemActualizar2;
    private javax.swing.JMenuItem itemBorrar;
    private javax.swing.JMenuItem itemBorrar1;
    private javax.swing.JMenuItem itemBorrar2;
    private javax.swing.JMenuItem itemCrear;
    private javax.swing.JMenuItem itemCrear1;
    private javax.swing.JMenuItem itemCrear2;
    private javax.swing.JMenu itemIngredientes;
    private javax.swing.JMenuItem itemLeer;
    private javax.swing.JMenuItem itemLeer1;
    private javax.swing.JMenuItem itemLeer2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuControlMateriaPrima;
    private javax.swing.JMenu menuControlProductos;
    private javax.swing.JMenu menuProduccion;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JPanel ventasycompras;
    // End of variables declaration//GEN-END:variables
}
